#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

mysql --user=adminuWJebAu --password=CbbTZnik1KrN --database=enigma53 < ~/app-root/repo/db.sql

#echo `pwd` > ~/app-root/runtime/repo/deploy.log