#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

echo `mysql --user=adminuWJebAu --password=CbbTZnik1KrN --database=enigma53 < ${OPENSHIFT_REPO_DIR}/db.sql`